services:
  - type: web
    name: telegram-target-bot
    env: python
    region: singapore
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn health_check:run_health_server & python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: telegram_target_bot
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8080
