services:
  - type: web
    name: telegram-target-bot
    env: python
    region: singapore
    plan: free
    healthCheckPath: /health
    autoDeploy: true
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: telegram_target_bot
      - key: PORT
        value: 8080
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
